### ISSUE TITLE
index error

### ISSUE THREAD

**Issue by pwlazy** [tuan3w/visual_search#7]
when i run
"python index_es.py --weight /work/misc/imagenet_weights --model_path /work/misc/faster_rcnn_models --input /work/misc/data/"

there is a error below

"  File "index_es.py", line 14, in <module>
    from extractor import Extractor
  File "/root/work/visual_search/visual_search/extractor.py", line 2, in <module>
    from model.test import extract_regions_and_feats \
  File "/root/work/visual_search/visual_search/lib/model/test.py", line 14, in <module>
    from utils.cython_nms import nms, nms_new
ImportError: No module named cython_nms"

how can i solve it? please help

**Comment by tuan3w** [comment]
Hi @pwlazy ,
You have to build nms module firstly. See my reply in the end of  #3 .

**Comment by pwlazy** [comment]
1) i run the script
  `cd visual_search/visual_search/lib/`
  `make`

there is a error blow 

python setup.py build_ext --inplace
Traceback (most recent call last):
  File "setup.py", line 55, in <module>
    CUDA = locate_cuda()
  File "setup.py", line 43, in locate_cuda
    raise EnvironmentError('The nvcc binary could not be '
EnvironmentError: The nvcc binary could not be located in your $PATH. Either add it to your path, or set $CUDAHOME
Makefile:2: recipe for target 'all' failed
make: *** [all] Error 1

because no GPU is on my pc,so i don't install CUDA

2)  there is a reply which let me try
`python -c 'from utils.cython_nms import nms, nms_new'`

i tried, there is a error blow 

Traceback (most recent call last):
  File "<string>", line 1, in <module>
ImportError: No module named cython_nms

3) there is other reply which said "install CUDA with only CPU"

there is no GPU on my pc, if i don't install CUDA , how can i solve it 

4) there is another reply which said "change setup.py and nms_wrapper.py",but it don't tell "how to change"

**Comment by tuan3w** [comment]
You can fix file `setup.py` as in [link](https://gist.github.com/tuan3w/bbabd560297bddcb6c1baa839688c2d0)
, then run 
````sh 
$ make
$ python -c 'from utils.cython_nms import nms, nms_new'
````
to make sure no error happens.

**Comment by pwlazy** [comment]
"make " and "python -c 'from utils.cython_nms import nms, nms_new'" now is OK ,thanks!

but ,when i run
"python index_es.py --weight /work/misc/imagenet_weights --model_path /work/misc/faster_rcnn_models --input /work/misc/data/"

another error appears
Traceback (most recent call last):
  File "index_es.py", line 14, in <module>
    from extractor import Extractor
  File "/root/work/visual_search/visual_search/extractor.py", line 11, in <module>
    from nets.vgg16 import vgg16
  File "/root/work/visual_search/visual_search/lib/nets/vgg16.py", line 16, in <module>
    from layer_utils.proposal_layer import proposal_layer
  File "/root/work/visual_search/visual_search/lib/layer_utils/proposal_layer.py", line 10, in <module>
    from model.nms_wrapper import nms
  File "/root/work/visual_search/visual_search/lib/model/nms_wrapper.py", line 9, in <module>
    from nms.gpu_nms import gpu_nms
ImportError: No module named gpu_nms

**Comment by tuan3w** [comment]
Since you haven't built gpu module yet, so when you call import module, this error throws. You have to  change `/visual_search/lib/model/nms_wrapper.py` file to make sure only cpu module is used.

**Comment by pwlazy** [comment]
i change '/visual_search/lib/model/nms_wrapper.py'  to comment the line 'from nms.gpu_nms import gpu_nm' , it's ok

another error appeared

root@7cb4b49eb272:~/work/visual_search/visual_search# python index_es.py --weight /root/work/misc/imagenet_weights/vgg16.weights  --model_path /root/work/misc/faster_rcnn_models --input /root/work/misc/data/
2017-11-17 01:19:39.288605: W tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use SSE4.1 instructions, but these are available on your machine and could speed up CPU computations.
2017-11-17 01:19:39.288674: W tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use SSE4.2 instructions, but these are available on your machine and could speed up CPU computations.
2017-11-17 01:19:39.288688: W tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use AVX instructions, but these are available on your machine and could speed up CPU computations.
2017-11-17 01:19:39.288700: W tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use AVX2 instructions, but these are available on your machine and could speed up CPU computations.
2017-11-17 01:19:39.288711: W tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use FMA instructions, but these are available on your machine and could speed up CPU computations.
Namespace(es_host='localhost', es_index='im_data', es_port=9200, es_type='obj', input='/root/work/misc/data/', model_path='/root/work/misc/faster_rcnn_models', weight='/root/work/misc/imagenet_weights/vgg16.weights')
Loading caffe weights...
Done!
Traceback (most recent call last):
  File "index_es.py", line 104, in <module>
    sess=sess)
  File "/root/work/visual_search/visual_search/extractor.py", line 53, in __init__
    tag='default', anchor_scales=anchors)
  File "/root/work/visual_search/visual_search/lib/nets/vgg16.py", line 496, in create_architecture
    rois, cls_prob, bbox_pred = self._vgg16_from_imagenet(sess, training)
  File "/root/work/visual_search/visual_search/lib/nets/vgg16.py", line 347, in _vgg16_from_imagenet
    rpn_cls_score_reshape = self._reshape_layer(rpn_cls_score, 2, "rpn_cls_score_reshape")
  File "/root/work/visual_search/visual_search/lib/nets/vgg16.py", line 178, in _reshape_layer
    reshaped = tf.reshape(to_caffe, tf.concat(0, [[self._batch_size], [num_dim, -1], [input_shape[2]]]))
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/ops/array_ops.py", line 1029, in concat
    dtype=dtypes.int32).get_shape(
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/ops.py", line 639, in convert_to_tensor
    as_ref=False)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/ops.py", line 704, in internal_convert_to_tensor
    ret = conversion_func(value, dtype=dtype, name=name, as_ref=as_ref)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/ops/array_ops.py", line 905, in _autopacking_conversion_function
    return _autopacking_helper(v, inferred_dtype, name or "packed")
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/ops/array_ops.py", line 868, in _autopacking_helper
    return gen_array_ops._pack(elems_as_tensors, name=scope)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/ops/gen_array_ops.py", line 1889, in _pack
    result = _op_def_lib.apply_op("Pack", values=values, axis=axis, name=name)


  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/op_def_library.py", line 768, in apply_op
    op_def=op_def)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/ops.py", line 2338, in create_op
    set_shapes_for_outputs(ret)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/ops.py", line 1719, in set_shapes_for_outputs
    shapes = shape_func(op)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/ops.py", line 1669, in call_with_requiring
    return call_cpp_shape_fn(op, require_shape_fn=True)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/common_shapes.py", line 610, in call_cpp_shape_fn
    debug_python_shape_fn, require_shape_fn)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/common_shapes.py", line 676, in _call_cpp_shape_fn_impl
    raise ValueError(err.message)
ValueError: Dimension 0 in both shapes must be equal, but are 2 and 1
	From merging shape 1 with other shapes. for 'vgg16_default/rpn_cls_score_reshape/concat/concat_dim' (op: 'Pack') with input shapes: [1], [2], [1].

**Comment by tuan3w** [comment]
I'm not sure what makes this problem. Maybe you used wrong tensorflow version. You have to use tensorflow `0.12.1`, newer version will not work.

**Comment by epopos** [comment]
@pwlazy I have the same mistake as you, have you solved it?

**Comment by epopos** [comment]
@tuan3w 
I downloaded faster_rcnn_models.tgz and imagenet_weights.tgz
Then Unpack them.
![40130b52-d217-4056-8352-9e2ad2a40d1c](https://user-images.githubusercontent.com/5657784/35978811-a1bd8314-0d21-11e8-82e9-905d42f94026.png)

export WEIGHT_PATH=/search/visual_search-master/visual_search/models/imagenet_weights/vgg16.weights
export MODEL_PATH=?
export INPUT=/search/input.png
cd visual_search
python index_es.py --weight $WEIGHT_PATH --model_path $MODEL_PATH --input $INPUT

But I don't know that how to set MODEL_PATH
I didn't find "vgg16_faster_rcnn_iter_490000.ckpt"
How shoud I do ? Thank you very much

**Comment by tuan3w** [comment]
Hi @epopos,
You should set MODEL_PATH=/search/visual_search-master/visual_search/models/faster_rcnn_models/coco_2014_train+coco_2014_valminusminival/default/vgg16_faster_rcnn_iter_490000.ckpt .

**Comment by epopos** [comment]
Hi @tuan3w 
Thank you for your reply 
I run like this 
python index_es.py --weight /search/visual_search-master/visual_search/models/imagenet_weights/vgg16.weights --model_path /search/visual_search-master/visual_search/models/faster_rcnn_models/coco_2014_train+coco_2014_valminusminival/default/vgg16_faster_rcnn_iter_490000.ckpt --input /home/chinese-ocr-master/test/2.jpg

Then I got error like this

![error](https://user-images.githubusercontent.com/5657784/35981917-768289b2-0d29-11e8-8f58-7c7eff88996d.png)

**Comment by tuan3w** [comment]
Please verify that your version of tensorflow you used is `0.12.1` . This pretrained is old, so it will not work with newer tensorflow version.

**Comment by epopos** [comment]
@tuan3w Thank you
I have installed  tensorflow 0.12.1 
   pip install  tensorflow==0.12.1
![e1](https://user-images.githubusercontent.com/5657784/35984589-bcf602d8-0d2f-11e8-91df-77bcbb078f33.jpg)

Then I run again
Got error 
![e2](https://user-images.githubusercontent.com/5657784/35984734-00049ee0-0d30-11e8-803c-0ca2f0122cfe.jpeg)

Then I installed glibc2.16  
Run again
![e3](https://user-images.githubusercontent.com/5657784/35985042-a943fd0c-0d30-11e8-9930-66d1a920b198.jpg)

![e4](https://user-images.githubusercontent.com/5657784/35985670-22385234-0d32-11e8-8cff-504ef39dfc54.png)

![e9](https://user-images.githubusercontent.com/5657784/35986792-fd1e36a0-0d34-11e8-982e-708c10121b3f.png)


It looks work well. But when I choosed a file and clicked search button.

Then I got error
![e10](https://user-images.githubusercontent.com/5657784/35987227-19003ea8-0d36-11e8-8a09-2f770b364bee.png)


Maybe I made sth wrong with elasticsearch. I will continue to solve it.  If you know the reason, you can tell me.
Thanks again.

**Comment by tuan3w** [comment]
Did you index data yet ? The error here is that index `im_data` isn't exist in elasticsearch. Try this to create schema and then index data to elasticsearch.
```bash
$ curl -XPUT http://localhost:9200/im_data -d @schema_es.json
```
Notice that it's `im_data` not `img_data` like in README. It's a mistake :))

**Comment by epopos** [comment]
@tuan3w  
 :)) You are right.  
 I  run   curl -XPUT http://localhost:9200/im_data -d @schema_es.json again
it works well. Thank you for your help.
