### ISSUE TITLE
Could not find plugin class

### ISSUE THREAD

**Issue by FMsunyh** [tuan3w/visual_search#8]
I got an exception when i run ./bin/elasticsearch.
I install the plugin in my local elastic. i did't use the docker.
Could you give me some ideas?
Error:
[2017-11-16T16:53:20,829][WARN ][o.e.b.ElasticsearchUncaughtExceptionHandler] [] uncaught exception in thread [main]
org.elasticsearch.bootstrap.StartupException: ElasticsearchException[Could not find plugin class [com.vcc.bigdata.elasticsearch.plugin.EsScorerPlugin]]; nested: ClassNotFoundException[com.vcc.bigdata.elasticsearch.plugin.EsScorerPlugin];
	at org.elasticsearch.bootstrap.Elasticsearch.init(Elasticsearch.java:125) ~[elasticsearch-5.2.0.jar:5.2.0]
	at org.elasticsearch.bootstrap.Elasticsearch.execute(Elasticsearch.java:112) ~[elasticsearch-5.2.0.jar:5.2.0]
	at org.elasticsearch.cli.SettingCommand.execute(SettingCommand.java:54) ~[elasticsearch-5.2.0.jar:5.2.0]
	at org.elasticsearch.cli.Command.mainWithoutErrorHandling(Command.java:122) ~[elasticsearch-5.2.0.jar:5.2.0]
	at org.elasticsearch.cli.Command.main(Command.java:88) ~[elasticsearch-5.2.0.jar:5.2.0]
	at org.elasticsearch.bootstrap.Elasticsearch.main(Elasticsearch.java:89) ~[elasticsearch-5.2.0.jar:5.2.0]
	at org.elasticsearch.bootstrap.Elasticsearch.main(Elasticsearch.java:82) ~[elasticsearch-5.2.0.jar:5.2.0]
Caused by: org.elasticsearch.ElasticsearchException: Could not find plugin class [com.vcc.bigdata.elasticsearch.plugin.EsScorerPlugin]
	at org.elasticsearch.plugins.PluginsService.loadPluginClass(PluginsService.java:366) ~[elasticsearch-5.2.0.jar:5.2.0]
	at org.elasticsearch.plugins.PluginsService.loadBundles(PluginsService.java:335) ~[elasticsearch-5.2.0.jar:5.2.0]
	at org.elasticsearch.plugins.PluginsService.<init>(PluginsService.java:132) ~[elasticsearch-5.2.0.jar:5.2.0]
	at org.elasticsearch.node.Node.<init>(Node.java:297) ~[elasticsearch-5.2.0.jar:5.2.0]
	at org.elasticsearch.node.Node.<init>(Node.java:232) ~[elasticsearch-5.2.0.jar:5.2.0]
	at org.elasticsearch.bootstrap.Bootstrap$6.<init>(Bootstrap.java:241) ~[elasticsearch-5.2.0.jar:5.2.0]
	at org.elasticsearch.bootstrap.Bootstrap.setup(Bootstrap.java:241) ~[elasticsearch-5.2.0.jar:5.2.0]
	at org.elasticsearch.bootstrap.Bootstrap.init(Bootstrap.java:333) ~[elasticsearch-5.2.0.jar:5.2.0]
	at org.elasticsearch.bootstrap.Elasticsearch.init(Elasticsearch.java:121) ~[elasticsearch-5.2.0.jar:5.2.0]
	... 6 more
Caused by: java.lang.ClassNotFoundException: com.vcc.bigdata.elasticsearch.plugin.EsScorerPlugin
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381) ~[?:1.8.0_141]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424) ~[?:1.8.0_141]
	at java.net.FactoryURLClassLoader.loadClass(URLClassLoader.java:814) ~[?:1.8.0_141]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357) ~[?:1.8.0_141]
	at org.elasticsearch.plugins.PluginsService.loadPluginClass(PluginsService.java:364) ~[elasticsearch-5.2.0.jar:5.2.0]
	at org.elasticsearch.plugins.PluginsService.loadBundles(PluginsService.java:335) ~[elasticsearch-5.2.0.jar:5.2.0]
	at org.elasticsearch.plugins.PluginsService.<init>(PluginsService.java:132) ~[elasticsearch-5.2.0.jar:5.2.0]
	at org.elasticsearch.node.Node.<init>(Node.java:297) ~[elasticsearch-5.2.0.jar:5.2.0]
	at org.elasticsearch.node.Node.<init>(Node.java:232) ~[elasticsearch-5.2.0.jar:5.2.0]
	at org.elasticsearch.bootstrap.Bootstrap$6.<init>(Bootstrap.java:241) ~[elasticsearch-5.2.0.jar:5.2.0]
	at org.elasticsearch.bootstrap.Bootstrap.setup(Bootstrap.java:241) ~[elasticsearch-5.2.0.jar:5.2.0]
	at org.elasticsearch.bootstrap.Bootstrap.init(Bootstrap.java:333) ~[elasticsearch-5.2.0.jar:5.2.0]
	at org.elasticsearch.bootstrap.Elasticsearch.init(Elasticsearch.java:121) ~[elasticsearch-5.2.0.jar:5.2.0]
	... 6 more

**Comment by tuan3w** [comment]
Hi @FMsunyh , 
It seems like you haven't installed  elasticsearch plugin yet. See README to known how to build plugin and install it.

**Comment by FMsunyh** [comment]
Hi @tuan3w 
Yes, i solved it. thank you.
